builds:
  - skip: true
release:
  prerelease: auto
  extra_files:
    - glob: ./telepace*.tgz
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'